---

- name: configure yp.conf file
  template:
    src: yp.conf.j2
    dest: /etc/yp.conf
    owner: root
    group: root
    mode: 644

- name: search ypdomainname
  command: ypdomainname
  register: ypdn
  ignore_errors: true

- name: exec ypdmainname
  command: ypdomainname {{domainname}}
  when: "ypdn.stdout.find('{{domainname}}') == -1"

- name: set nisdomain for redhat
  lineinfile:
    dest: /etc/sysconfig/network
    regexp: '^NISDOMAIN'
    line:  "NISDOMAIN={{domainname}}"
    state: present
  when: ansible_os_family == 'RedHat'

- name: set nisdomain for suse and ubuntu
  lineinfile:
    dest: /etc/defaultdomain
    line: "{{domainname}}\n"
    owner: root
    group: root
    mode: 644
    create: yes
    state: present
  when: (ansible_os_family == 'Suse' ) or
        (ansible_os_family == 'Debian' )
